pylint: update pylintrc based on the template from pylint 0.23.0
The previous version of pylintrc defined MASTER.ignore twice, which is
illegal in Python 3:

  $ pylint --rcfile=pylintrc pym/gentoolkit/helpers.py
  Traceback (most recent call last):
    ...
  configparser.DuplicateOptionError: While reading from pylintrc [line 24]:
    option 'ignore' in section 'MASTER' already exists

I kept other option values unchanged from the old pylintrc, and added
"# was ..." comments for each non-default value.