equery depends: Fix a traceback due to UnboundLocalError:
  File "/home/brian/Dev/git/gentoolkit/pym/gentoolkit/equery/depends.py"
      , line 106, in format_depend
    self.print_fn(indent, str(dep.cpv), use_conditional, formatted_dep)
UnboundLocalError: local variable 'formatted_dep' referenced before
    assignment

The statement appears to be added as preliminary debug info.
Removed it.

Signed-off-by: Brian Dolbec <dolsen@gentoo.org>